### ISSUE TITLE
Repository name

### ISSUE THREAD

**Issue by davidhedlund** [TripSit/welcome#2]
Should this repository be renamed to tripsit.me?

Or should I report bugs and freedback for tripsit.me somewhere else on https://github.com/TripSit ?

**Comment by powerjungle** [comment]
Well this repository is only for the welcome page present on: https://chat.tripsit.me/ (since it's code is separate from the main page)

If you have suggestions only for this page, this is the repository, otherwise checkout the other repositories here: https://github.com/TripSit/

**Comment by tacerus** [comment]
As @powerjungle already said this repo is for the "Welcome" application which serves https://chat.tripsit.me. The name is a bit misleading in that regard. Currently bugs and feedback can be reported directly on IRC in `#content` or via email. We will add a repo for Issues regarding to the current TripSit operations to be submitted in soon, currently there is only one for future/beta operations since we started reworking our GitHub only a day ago.
