### ISSUE TITLE
Make the wiki open for anyone to edit

### ISSUE THREAD

**Issue by davidhedlund** [TripSit/welcome#3]
Creating a user on [login](https://wiki.tripsit.me/wiki/Special:UserLogin) doesn't give you permission to edit the wiki. You have to ask someone to give you the permission.

Currently it's **extremly** hard to reach someone to give you editing permission to the wiki. I've tried a number of times and eventually gave up; This is completely counter productive and nonsense in my opinion. You waste the time of people that want to help, and you waste material that could be added to those people when they give up.

* Why is not the forum open to edit for anyone?

* Can you please give everyone edit permission?

* Can you at least add an email that can be used to request editing permission on the wiki; eg create admin@wiki.tripsit.me and add it to the [login](https://wiki.tripsit.me/wiki/Special:UserLogin) page?

**Comment by tacerus** [comment]
Hi,

closing this since it is old and in the wrong repo. We are currently working on improving things, change requests for the wiki can be communicated in our IRC channel `#content` or via the contact forms on our website.

Of course not everyone will be granted read access, since everything we publish gets verified first.
